### ISSUE TITLE
关于代码显示的问题

### ISSUE THREAD

**Issue by Doublemine** [SuperKieran/TKL#1]
你好，我在试用您这款精美的主题的时候，发现如果在博客中嵌入代码的话，会造成版面代码被滚动条夹在中间，和主题的格调不搭，请问可以修复吗？期待后续更新

**Comment by SuperKieran** [comment]
具体表现？有截图吗？不明白你说的情况

**Comment by Doublemine** [comment]
我在使用Markdown文本编辑器MdCharm编辑java代码的时候，该软件可以实时预览。如截图所示：![qq 20150405123233](https://cloud.githubusercontent.com/assets/11732925/6995776/9190a7c0-db90-11e4-837b-7a96ddbaa9d5.png)但是我使用您的主题生成静态文件，并且在本地预览的时候，又如截图所示:![qq 20150405123015](https://cloud.githubusercontent.com/assets/11732925/6995786/ae8d1822-db90-11e4-914f-871f8ed823bb.png)。我的hexo版本为3.0。我在浏览您的博客的时候，发现没有此问题。对此，我也很疑惑。期待您的回复。

**Comment by SuperKieran** [comment]
我重新安装了hexo3.0 并且直接用我的主题  原始配置没有做任何更改  都是正常的  无法复现你的情况 这应该和主题无关了 你可以对比下你的 _config.yml文件和原始的配置  有什么差别的地方 可能就是问题所在

**Comment by Doublemine** [comment]
重新安装HEXO3.0之后，不对_config.yml作任何修改直接引用您的主题。在Chrome 40.0.2214.115 (64-bit)上问题复现。但是我在换用IE 11 过后，问题即刻得到解决。可能是浏览器的兼容问题，但是我在用chrome浏览器浏览您的博客的时候，又没有因为浏览器的差异造成错误的排版。真是一个奇怪的问题啊。。

**Comment by Doublemine** [comment]
你好。经过多台电脑的浏览器测试，应该是我电脑的chrome的问题了。非常感谢作者您耐心的解答。祝主题越做越好。工作顺利。
