### ISSUE TITLE
https下的字体库

### ISSUE THREAD

**Issue by hellflame** [SuperKieran/TKL#13]
![](https://static.hellflame.net/f/d99c76b7d0/?raw=1)
360显然没有提供https下这样的资源
发现其实直接用google的速度也还是不错的样子
![](https://static.hellflame.net/f/188f275ef9/?raw=1)

**Comment by hellflame** [comment]
实际上在个人fork的版本中刚刚替换为google原始的字体库，不过自己的版本加了很多自己的东西，所以......好吧～我就是说说而已......

**Comment by jasoncheng911** [comment]
@hellflame 你仿佛在自言自语。呵呵。我也是把useso换成google反倒快了。。但最后我觉得直接删掉字体。好像又更快了。。。嘿

**Comment by hellflame** [comment]
删掉字体，少了请求，响应不是理所当然会快么，这是什么新鲜的值得说出来的事情么，，，

**Comment by jasoncheng911** [comment]
@hellflame 。。嘿，兄弟。貌似是我语气表达不妥让你误会了。（其实我只是感叹了一下别无他意）实在抱歉！祝你生活愉快。！
