### ISSUE TITLE
非常喜欢这个主题，但是我发现了一些问题

### ISSUE THREAD

**Issue by xcc3641** [SuperKieran/TKL#14]
- 标题出位
  ![image](https://cloud.githubusercontent.com/assets/11666634/13379215/66b5f37a-de5a-11e5-9fa6-cbae5aa03ae2.png)
- 代码块问题
  ![image](https://cloud.githubusercontent.com/assets/11666634/13379219/963ea772-de5a-11e5-80af-d27a130aeca4.png)

**Comment by SuperKieran** [comment]
标题出位可以在加号前后各加一个空格，不加空格强制换行得在css里把宽度写死，不推荐这样  
代码的问题貌似是在.md文件里每个空行得手动加一个空格 这是hexo的解析问题

**Comment by xcc3641** [comment]
> 加号前后各加一个空格 

这句话没明白诶。我写文章标题都是title: xxxx

**Comment by SuperKieran** [comment]
a + b + c
