### ISSUE TITLE
Hi 很感谢你的分享

### ISSUE THREAD

**Issue by seagullbird** [SuperKieran/TKL#16]
特别喜欢你的主题，用来装饰我的hexo博客了，希望你不会介意！

然后有个小问题，About me页面似乎没有在这个仓库里面？我该如何设置和你的demo一样的About 页面呢？真的很喜欢那个风格！我不是学前端的，这些不是很懂。谢谢指教！

**Comment by Forec** [comment]
build a directory under source and create an index.md to say what you want.

**Comment by seagullbird** [comment]
谢谢 解决了是在source下面添加about.md 
你应该看得懂中文吧
