### ISSUE TITLE
博客的评论有问题。

### ISSUE THREAD

**Issue by Abysssea** [SuperKieran/TKL#18]
谢谢你的Theme，很喜欢。

我去你博客，发现你的disqus和多说同时存在，我是翻墙浏览的你博客，不知道是就我一个人看这样，还是别人也这样。

**Comment by SuperKieran** [comment]
评论模块里加上disqus的通用代码就行了

**Comment by Abysssea** [comment]
亲，你误会了，我说的是**你的**博客里，下边有两个评论。。难道是故意做成这样的。。？
http://go.kieran.top/

**Comment by SuperKieran** [comment]
恩 故意....有人喜欢disqus 有人用多说  有时候多说会挂
