### ISSUE TITLE
文章分类页面渲染

### ISSUE THREAD

**Issue by hellflame** [SuperKieran/TKL#19]
首先是，文章分类页面在主题中不支持分页，其实我在看完了官方文档之后也不知道怎么做分页

官方给的`_config.yml`中有一个分页配置的选项

```
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
```

手贱给了默认每个分页10篇文章，然而这个主题不支持，导致我的文章分类列表最多只有10篇文章2333

最终只能 per_page：0

然后是在[源代码](https://github.com/SuperKieran/TKL/blob/master/layout/casper/archive.ejs)中的pagination不在官方给定的全局变量中，在渲染过程中也一直显示是`undefined`
![](http://7xp8li.com1.z0.glb.clouddn.com/issue-TKL.png)

`title`这个变量在一开始定义了，然后在后来就一直没有发挥过作用。。。。。

**Comment by hellflame** [comment]
好吧......`per_page`跟首页的分页又有关系，，，不知道怎么处理这个问题了2333

**Comment by SuperKieran** [comment]
pagination是上一个目录中的archive.ejs传入的 其实就是 config里的archive
per_page在config.yml里新增个变量 改下hexo-generator-archive模块的源码把新变量替换掉per_page 即可
