### ISSUE TITLE
hello,i want to know how could i add "duoshuo" comment in this theme

### ISSUE THREAD

**Issue by Bossyao168** [SuperKieran/TKL#2]
i want to add "duoshuo" comment in my blog with your theme,but I can't find the method of adding it, and I'm not good at using nodejs.Please tell me how could i add it easily.Thanks.

**Comment by SuperKieran** [comment]
login at http://duoshuo.com   you will get a duoshuo_id.  Add it in _config.yml.

**Comment by chenlinnan** [comment]
多说用不了。能不能详细讲一下 duoshuo id 指的是什么

**Comment by SuperKieran** [comment]
登录多说后台 工具里面的通用代码里的 {short_name:"xxxx"} xxxx就是

**Comment by chenlinnan** [comment]
擦。。你居然在线，我自己刚弄懂。。。谢谢了。不过好像格式被我改乱了。。。
我想改下页面拉下的速度和点开文章后不显示欢迎画面，就是已进入就看到的画面，你知道可以在哪里改吗
