### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by ValiantCat** [SuperKieran/TKL#22]
用开发者工具查看  http://fonts.gstatic.com  引用自这个网站的字体失败  请问在哪里更改呢

**Comment by jasoncheng911** [comment]
@aiqiuqiu 我也是这样的，因为很多字体加载失败，由于https的问题，导致网页加载跳转要等上接近1分钟出一个页面

**Comment by jasoncheng911** [comment]
@aiqiuqiu 你问题解决没？
