### ISSUE TITLE
文章正文鼠标无法选择文字，也不能点击链接

### ISSUE THREAD

**Issue by dangdangfeng** [SuperKieran/TKL#30]
您好，非常感谢您提供的模版。使用了您的模版后其它都很好，就是在文章的正文无法用鼠标选择文字和点击链接，感觉就像是图片一样，但是，如果网速不好的时候，就可以使用鼠标选择文字。我怀疑是不是加载了JS的处理，但是一直找不到解决的方法。我看您的博客里的文章是可以用鼠标选择文字的。不知您能否在百忙中帮我释疑下这个问题，万分感谢。

**Comment by SuperKieran** [comment]
Github上的主题直接使用没有复现这个bug...你看看你是否装了别的什么插件
