### ISSUE TITLE
为什么我的博客加载速度出奇的慢

### ISSUE THREAD

**Issue by jasoncheng911** [SuperKieran/TKL#34]
为什么我的博客加载速度出奇的慢，而楼主的demo却出奇的快，很捉急。请楼主快快答疑解惑。感激不尽！

**Comment by NoahDragon** [comment]
经测，确实比较慢。博主网站为http://yuancheng91.top
https://github.com/hexojs/hexo/issues/2345

**Comment by jasoncheng911** [comment]
@NoahDragon 我直接把head里面的字体引用删掉了，貌似快了一点，排除我首页放了一张高清图加载慢的原因。还是多谢你！

**Comment by SuperKieran** [comment]
更新了一下，字体替换成了Google字体库，并且异步加载
