### ISSUE TITLE
我想客制化一下首页的高度，请问在哪里调呀

### ISSUE THREAD

**Issue by jxust-CGS** [SuperKieran/TKL#39]
就是首页不是一张占满全屏的图片吗？我想让图片只占60%的高度就好了，在哪里调呢？

**Comment by changewade** [comment]
/TKL/source/css/style.css/
找到如下内容：

/* *******************************************************
* Full-height hero section, (homepage, above the fold,)
******************************************************* */

/* 首页图片（高100%，宽100%） */
#hero {
	height: 100%;
	position: fixed;
	width: 100%;
	padding-top: 0;
}
