### ISSUE TITLE
多说已死

### ISSUE THREAD

**Issue by ReverseScale** [SuperKieran/TKL#45]
好人，什么时候出更新啊

**Comment by SuperKieran** [comment]
更新啥

**Comment by ReverseScale** [comment]
多说评论 死了... 要不要来个高大上的评论啊...

**Comment by SuperKieran** [comment]
慌不要慌... 你认为的高大上是什么样子的呢

**Comment by ReverseScale** [comment]
Gitment 网上看到的，可以考虑哦，其实我就是试着留个言，哈哈
(
Gitment 是作者实现的一款基于 GitHub Issues 的评论系统。
主要面向程序员群体，尤为适合各种静态博客和项目页面。
Gitment 包括以下特性：
在前端直接引入，不需要任何后端代码
使用 GitHub 账号登录
可以在页面进行查看、发送评论，点赞，@ 等操作
可以在 GitHub 进行编辑、删除评论等操作
有完整的 Markdown / GFM 支持
支持代码高亮
基于 GitHub 的通知
易于自定义
)

**Comment by SuperKieran** [comment]
这个别人已经写了 照着作者写的使用方法直接拿来用就行了 也不需要我更新什么

**Comment by ReverseScale** [comment]
恩恩，那好的，依然感谢哦
