### ISSUE TITLE
没有样式。

### ISSUE THREAD

**Issue by whiteineyes** [SuperKieran/TKL#49]
切换成TKL后，变得没有样式了。但是查看源代码却有代码。
![n 7 4 5urvew z 7y 8 a](https://user-images.githubusercontent.com/9414889/31575862-4d225790-b122-11e7-9921-a3795eb04fd9.png)
![b16k1ej_epj473ux oy ne](https://user-images.githubusercontent.com/9414889/31575874-897ad73a-b122-11e7-979a-1eaabf9f91f2.png)

**Comment by SuperKieran** [comment]
用 hexo s 命令查看博客
