### ISSUE TITLE
上报个BUG,代码框会自动生成序号,这个序号会产生连续数字,这个数字会在首页溢出

### ISSUE THREAD

**Issue by gclinux** [SuperKieran/TKL#51]
http://gclinux.github.io/
如上面
代码框里面的数字溢出来了 比较难看

**Comment by SuperKieran** [comment]
已修复

**Comment by xinshangshangxin** [comment]
@SuperKieran 
首页 依然 有 连续数字, 如何去除?
或者  支持 

```
---
layout: post
title: ''
description: ' 把这里的内容显示到首页上???'
date:
tags:
---
```

**Comment by SuperKieran** [comment]
@xinshangshangxin  https://github.com/SuperKieran/TKL/commit/b721e2f9d745d7939254dbfd13a95b7b2ca05c68
你可以先照着这个改一下....我发现后面被我改回去了
