### ISSUE TITLE
首页显示博客内容时有问题

### ISSUE THREAD

**Issue by grace618** [SuperKieran/TKL#59]
会选取前220个字，但是，如果前220个字有代码时，首页显示博客那里会显示12345678910这种代码行

例如
1.新建components/SvgIcon.vue组件 使用的是阿里巴巴的iconfont图标库，有三种方式可以引用，我使用的是symbol方式 12345678910111213141516171819202122232425262728293031323334353637383940414243<template> <svg :class="svgClass" aria-hidde

**Comment by SuperKieran** [comment]
可以在文章里加 `<!--more-->` 显式指定摘要部分，这也首页的摘要会带样式，代码部分也会正常
