### ISSUE TITLE
unable overide config, especially the bottom_saying.

### ISSUE THREAD

**Issue by enter-rebel** [SuperKieran/TKL#60]
I just test with the bottom_saying, and somehow I am expecting that I can override the config via the main config.
without going deeper to theme-specific config.

Let me thank you for, great theme, simple but stylish.

**Comment by SuperKieran** [comment]
> I just test with the bottom_saying, and somehow I am expecting that I can override the config via the main config.
> without going deeper to theme-specific config.
> 
> Let me thank you for, great theme, simple but stylish.

https://github.com/SuperKieran/TKL/blob/bbd571adba1b233a3a28610554daeeffac6d4c66/layout/_partial/index.ejs#L69
Change `theme.bottom_saying` to `config.bottom_saying`.
