### ISSUE TITLE
文章内下一篇文章或者上一篇文章链接失效

### ISSUE THREAD

**Issue by gitwizChen** [SuperKieran/TKL#7]
href="<%- url_for(page.prev.path) %>"最后编译后得到的总是href="../index.html"，导致链接失效，不知道为什么

**Comment by SuperKieran** [comment]
无法复现  如果没有具体实例的话 我无法修复

**Comment by gitwizChen** [comment]
额，我再看看自己能不能用其他方式修复，谢谢啦
